# Generated by Django 5.2.3 on 2025-06-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Shark Tower', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('precio_final_pactado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda_pactada', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], max_length=3)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda_pagada', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, help_text='Si el pago es en USD, registrar el tipo de cambio a MXN de ese día. Si es en MXN, poner 1.', max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='UPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: Departamento 501, Lote 23', max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total de la unidad', max_digits=12)),
                ('moneda', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='USD', max_length=3)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendida', 'Vendida'), ('Pagada', 'Pagada y Entregada'), ('Bloqueada', 'Bloqueada')], default='Disponible', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upes', to='api.proyecto')),
            ],
            options={
                'unique_together': {('proyecto', 'identificador')},
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='upe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='api.upe'),
        ),
    ]
