# Generated by Django 5.2.3 on 2025-06-23 19:00

# En el nuevo archivo de migración (ej: 0003_create_dashboard_permission.py)

from django.db import migrations


def create_dashboard_permission(apps, schema_editor):
    """Crea el permiso para ver el dashboard."""
    from django.contrib.auth.models import Permission
    from django.contrib.contenttypes.models import ContentType

    # Usamos un modelo existente (como Proyecto) para "anclar" el permiso,
    # aunque no esté directamente relacionado con él.
    content_type = ContentType.objects.get_for_model(
        apps.get_model('api', 'Proyecto'))

    Permission.objects.create(
        codename='can_view_dashboard',
        name='Puede ver el dashboard',
        content_type=content_type,
    )


def remove_dashboard_permission(apps, schema_editor):
    """Elimina el permiso para ver el dashboard."""
    from django.contrib.auth.models import Permission
    Permission.objects.filter(codename='can_view_dashboard').delete()


class Migration(migrations.Migration):

    dependencies = [
        # Asegúrate que el nombre de la migración anterior sea correcto
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dashboard_permission,
                             remove_dashboard_permission),
    ]
