# Generated by Django 6.0 on 2025-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Luximia ERP', max_length=100)),
                ('logo_login', models.ImageField(blank=True, null=True, upload_to='config/logos/')),
                ('logo_ticket', models.ImageField(blank=True, help_text='Logo B/N optimizado para impresión térmica', null=True, upload_to='config/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='config/logos/')),
                ('iva_default', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='IVA por defecto (%)')),
                ('moneda_base', models.CharField(choices=[('MXN', 'Peso Mexicano (MXN)'), ('USD', 'Dólar Americano (USD)')], default='MXN', max_length=3)),
                ('retencion_isr', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Retención ISR (%)')),
                ('mensaje_ticket_pie', models.TextField(blank=True, default='Gracias por su compra', help_text='Mensaje al final de los tickets')),
                ('dias_vencimiento_cotizacion', models.IntegerField(default=15, help_text='Días de validez para cotizaciones')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
    ]
