# Generated by Django 6.0 on 2026-01-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featureflag_systemsetting'),
        ('notifications', '0002_notificacion_delete_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL donde se enviará el POST')),
                ('activo', models.BooleanField(default=True)),
                ('eventos', models.JSONField(default=list, help_text="Lista de eventos: ['ALERT_OBRA', 'DAILY_BRIEFING', 'STOCK_CRITICAL']")),
                ('secret_token', models.CharField(blank=True, help_text='Token para validar autenticidad en el destino', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.empresa')),
            ],
        ),
    ]
