# Generated by Django 6.0 on 2025-12-17 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(help_text='Código interno (ej. P001)', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PERCEPCION', 'Percepción'), ('DEDUCCION', 'Deducción'), ('OTRO_PAGO', 'Otro Pago')], max_length=20)),
                ('es_fiscal', models.BooleanField(default=True, help_text='Si es false, es solo para control interno (Pagadora).')),
                ('clave_sat', models.CharField(blank=True, help_text='Clave Agrupadora SAT (c_TipoPercepcion/Deduccion)', max_length=20, null=True)),
                ('es_periodico', models.BooleanField(default=True, help_text='Se aplica en cada nómina ordinaria automáticamente.')),
                ('grava_isr', models.BooleanField(default=True, help_text='Si suma a la base gravable de ISR.')),
                ('grava_imss', models.BooleanField(default=True, help_text='Si integra al Salario Base de Cotización (SBC).')),
                ('cuenta_contable', models.CharField(blank=True, help_text='Integración con Contabilidad.', max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('valor_uma', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor UMA Diario')),
                ('valor_umi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor UMI (Infonavit)')),
                ('salario_minimo_general', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Mínimo General')),
                ('salario_minimo_frontera', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Mínimo Frontera')),
                ('porc_imss_enfermedad_maternidad_obrero', models.DecimalField(decimal_places=3, default=0.25, max_digits=5, verbose_name='% E.M. Gastos Médicos (Obrero)')),
                ('porc_imss_invalidez_vida_obrero', models.DecimalField(decimal_places=3, default=0.625, max_digits=5, verbose_name='% Invalidez y Vida (Obrero)')),
                ('porc_imss_cesantia_vejez_obrero', models.DecimalField(decimal_places=3, default=1.125, max_digits=5, verbose_name='% Cesantía y Vejez (Obrero)')),
                ('porc_imss_enfermedad_excedente_obrero', models.DecimalField(decimal_places=3, default=0.4, max_digits=5, verbose_name='% E.M. Excedente 3 UMA (Obrero)')),
                ('cuota_fija_imss_patron', models.DecimalField(decimal_places=2, default=20.4, max_digits=6, verbose_name='Cuota Fija Patronal')),
                ('porc_imss_enfermedad_maternidad_patron', models.DecimalField(decimal_places=3, default=0.7, max_digits=5, verbose_name='% E.M. Gastos Médicos (Patrón)')),
                ('porc_imss_invalidez_vida_patron', models.DecimalField(decimal_places=3, default=1.75, max_digits=5, verbose_name='% Invalidez y Vida (Patrón)')),
                ('porc_imss_cesantia_vejez_patron', models.DecimalField(decimal_places=3, default=3.15, max_digits=5, verbose_name='% Cesantía y Vejez (Patrón)')),
                ('porc_imss_guarderia_prestaciones_patron', models.DecimalField(decimal_places=3, default=1.0, max_digits=5, verbose_name='% Guarderías y Prestaciones (Patrón)')),
                ('porc_imss_riesgo_trabajo_patron', models.DecimalField(decimal_places=3, default=0.5, help_text='Este varía por empresa, este es el mínimo de ley.', max_digits=5, verbose_name='% Riesgo Trabajo (Patrón Base)')),
                ('porc_imss_retiro_patron', models.DecimalField(decimal_places=3, default=2.0, max_digits=5, verbose_name='% Retiro (Patrón)')),
                ('porc_infonavit_patron', models.DecimalField(decimal_places=3, default=5.0, max_digits=5, verbose_name='% INFONAVIT (Patrón)')),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('EXTRAORDINARIA', 'Extraordinaria')], default='ORDINARIA', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADA', 'Calculada'), ('TIMBRADA', 'Timbrada/Cerrada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('total_percepciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('razon_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.razonsocial')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReciboNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('salario_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sbc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('antiguedad_dias', models.IntegerField(default=0)),
                ('dias_pagados', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos_retenidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imss_retenido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('uuid_sat', models.CharField(blank=True, help_text='Folio Fiscal Digital', max_length=36, null=True)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='rrhh.nomina')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'unique_together': {('nomina', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='DetalleReciboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_sat', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_concepto', models.CharField(max_length=200)),
                ('monto_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_exento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.conceptonomina')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rrhh.recibonomina')),
            ],
            options={
                'verbose_name': 'Detalle de Concepto',
                'verbose_name_plural': 'Detalles de Conceptos',
            },
        ),
        migrations.CreateModel(
            name='SubsidioEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('anio_vigencia', models.PositiveIntegerField(default=2025)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenglonSubsidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_hasta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_subsidio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tabla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='rrhh.subsidioempleo')),
            ],
            options={
                'ordering': ['ingreso_hasta'],
            },
        ),
        migrations.CreateModel(
            name='TablaISR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('anio_vigencia', models.PositiveIntegerField(default=2025)),
                ('tipo_periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('QUINCENAL', 'Quincenal'), ('SEMANAL', 'Semanal'), ('ANUAL', 'Anual')], max_length=20)),
                ('descripcion', models.CharField(help_text='Ej. Tabla ISR Mensual 2025', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenglonTablaISR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, help_text='Null para infinito', max_digits=12, null=True)),
                ('cuota_fija', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_excedente', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tabla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='rrhh.tablaisr')),
            ],
            options={
                'ordering': ['limite_inferior'],
            },
        ),
    ]
