# Generated by Django 6.0 on 2025-12-18 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_conceptonomina_configuracioneconomica_nomina_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaCentralizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('archivo_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('esquema', models.CharField(default='FISCAL', max_length=50)),
                ('tipo', models.CharField(default='QUINCENAL', max_length=50)),
                ('periodo', models.CharField(default='1', max_length=50)),
                ('empresa', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('puesto', models.CharField(blank=True, max_length=200, null=True)),
                ('neto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sueldo_diario', models.DecimalField(decimal_places=2, default=0, help_text='SDO', max_digits=12)),
                ('dias_trabajados', models.DecimalField(decimal_places=2, default=0, help_text='DIAS', max_digits=5)),
                ('sueldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prima_vacacional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aguinaldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retroactivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subsidio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('isr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prestamo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('infonavit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('isn', models.DecimalField(decimal_places=2, default=0, help_text='Impuesto Sobre Nómina', max_digits=12)),
                ('previo_costo_social', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_carga_social', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_nomina', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nominas_y_costos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_facturacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
