# Generated by Django 6.0 on 2025-12-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_nominacentralizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominacentralizada',
            name='total_percepciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
