# Generated by Django 6.0 on 2025-12-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_nominacentralizada_total_percepciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominacentralizada',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
