# Generated by Django 6.0 on 2025-12-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_nominacentralizada_neto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('tipo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal')], max_length=20, verbose_name='Tipo de Nómina')),
                ('numero', models.IntegerField(verbose_name='Número de Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Periodo de Nómina',
                'verbose_name_plural': 'Periodos de Nómina',
                'ordering': ['anio', 'tipo', 'numero'],
                'unique_together': {('anio', 'tipo', 'numero')},
            },
        ),
    ]
