# Generated by Django 6.0 on 2025-12-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_documentoexpediente_incapacidad_solicitudpermiso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='no_empleado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='No. Colaborador'),
        ),
        migrations.AddField(
            model_name='empleadodatoslaborales',
            name='bonos_excedentes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bonos y Excedentes'),
        ),
        migrations.AddField(
            model_name='empleadodatoslaborales',
            name='horario_turno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario o Turno'),
        ),
        migrations.AddField(
            model_name='empleadodatoslaborales',
            name='registro_patronal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleadodatoslaborales',
            name='tipo_nomina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleadodatoslaborales',
            name='tipo_salario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleadodatoslaborales',
            name='tipo_trabajador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleadodetallepersonal',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleadodetallepersonal',
            name='estatus_educativo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus Educativo'),
        ),
        migrations.AddField(
            model_name='empleadodetallepersonal',
            name='grado_estudios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grado Máximo de Estudios'),
        ),
        migrations.AddField(
            model_name='empleadodetallepersonal',
            name='padecimientos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleadodetallepersonal',
            name='tratamiento_actual',
            field=models.TextField(blank=True, null=True, verbose_name='Tratamiento o Medicación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
