# Generated by Django 6.0 on 2025-12-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_buzonimss'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibonomina',
            name='uuid',
            field=models.CharField(blank=True, help_text='Folio Fiscal SAT (Alias)', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='xml_timbrado',
            field=models.TextField(blank=True, help_text='XML con el complemento de timbre', null=True),
        ),
    ]
