# Generated by Django 6.0 on 2026-01-03 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featureflag_systemsetting'),
        ('rrhh', '0010_recibonomina_uuid_recibonomina_xml_timbrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrotrabajo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='razonsocial',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='razonsocial',
            name='nombre_o_razon_social',
            field=models.CharField(max_length=200),
        ),
    ]
