# Generated by Django 6.0 on 2026-01-03 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featureflag_systemsetting'),
        ('rrhh', '0011_centrotrabajo_empresa_departamento_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptonomina',
            name='cuenta_contable',
        ),
        migrations.RemoveField(
            model_name='conceptonomina',
            name='es_fiscal',
        ),
        migrations.RemoveField(
            model_name='conceptonomina',
            name='es_periodico',
        ),
        migrations.RemoveField(
            model_name='conceptonomina',
            name='grava_imss',
        ),
        migrations.RemoveField(
            model_name='conceptonomina',
            name='grava_isr',
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='es_fijo',
            field=models.BooleanField(default=False, help_text='Si se aplica automáticamente en cada periodo'),
        ),
        migrations.AddField(
            model_name='empleadodatoslaborales',
            name='regimen_contratacion',
            field=models.CharField(blank=True, help_text='Catálogo SAT c_RegimenContratacion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conceptonomina',
            name='clave_sat',
            field=models.CharField(blank=True, help_text='Código del catálogo SAT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='conceptonomina',
            name='codigo',
            field=models.CharField(help_text='Ej: P001, D001', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='conceptonomina',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conceptonomina',
            name='tipo',
            field=models.CharField(choices=[('PERCEPCION', 'Percepción'), ('DEDUCCION', 'Deducción'), ('OTRO_PAGO', 'Otros Pagos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='empleadodocumentacionoficial',
            name='tipo_regimen',
            field=models.CharField(blank=True, help_text='Ej: Sueldos y Salarios', max_length=100, null=True),
        ),
    ]
