# Generated by Django 6.0 on 2026-01-03 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featureflag_systemsetting'),
        ('obras', '0002_obra_empresa'),
        ('rrhh', '0012_remove_conceptonomina_cuenta_contable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('incidencia', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('FALTA', 'Falta'), ('RETARDO', 'Retardo'), ('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad')], default='ASISTENCIA', max_length=20)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('BIOMETRICO', 'Biométrico'), ('WHATSAPP_BOT', 'WhatsApp Bot')], default='MANUAL', max_length=20)),
                ('ubicacion_gps', models.CharField(blank=True, help_text='Lat,Lon', max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='rrhh.empleado')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('empleado', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='DistribucionCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('porcentaje', models.IntegerField(default=100, help_text='Porcentaje del costo diario asignado a esta obra/CC')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='rrhh.asistencia')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.centrocosto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_nomina', to='obras.obra')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Distribución de Costo',
                'verbose_name_plural': 'Distribuciones de Costos',
            },
        ),
    ]
