# Generated by Django 6.0 on 2026-01-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_asistencia_distribucioncosto'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominacentralizada',
            name='fecha_timbrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominacentralizada',
            name='uuid',
            field=models.CharField(blank=True, help_text='Folio Fiscal (UUID)', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='nominacentralizada',
            name='xml_timbrado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
