# Generated by Django 6.0 on 2026-01-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_porcentaje_anticipo_and_more'),
        ('rrhh', '0014_nominacentralizada_fecha_timbrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucioncosto',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_asistencia', to='obras.actividadproyecto'),
        ),
    ]
