# Generated by Django 6.0 on 2026-01-04 02:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0008_almacen_empresa_insumo_stock_minimo'),
        ('obras', '0002_obra_empresa'),
        ('rrhh', '0014_nominacentralizada_fecha_timbrado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(help_text='Código interno, Placa o QR', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, help_text='Número de Serie del Fabricante', max_length=100, null=True)),
                ('fecha_adquisicion', models.DateField(default=datetime.date.today)),
                ('costo_adquisicion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('factura_uuid', models.CharField(blank=True, help_text='UUID de la factura de compra', max_length=36, null=True)),
                ('vida_util_anios', models.IntegerField(default=10)),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, help_text='Valor estimado al final de su vida útil', max_digits=14)),
                ('valor_actual', models.DecimalField(decimal_places=2, default=0, help_text='Valor en libros actual', max_digits=14)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso / Asignado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Baja / Vendido / Desechado')], default='DISPONIBLE', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('obra_actual', models.ForeignKey(blank=True, help_text='Ubicación física actual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to='obras.obra')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.proveedor')),
                ('responsable_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_resguardados', to='rrhh.empleado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_retorno', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='activos.activofijo')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empleado_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.empleado')),
                ('obra_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='obras.obra')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje_depreciacion_anual', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje sugerido de depreciación anual (0-100)', max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Categoría de Activo',
                'verbose_name_plural': 'Categorías de Activos',
            },
        ),
        migrations.AddField(
            model_name='activofijo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.categoriaactivo'),
        ),
        migrations.CreateModel(
            name='HistorialDepreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto depreciado este periodo', max_digits=12)),
                ('valor_libro_anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_libro_nuevo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('poliza_generada', models.CharField(blank=True, help_text='Folio de la póliza contable', max_length=50, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones', to='activos.activofijo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Historial de Depreciación',
                'verbose_name_plural': 'Historial de Depreciaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Mantenimiento Correctivo'), ('EMERGENCIA', 'Reparación de Emergencia')], default='PREVENTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('fecha_programada', models.DateField()),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('kilometraje', models.IntegerField(blank=True, help_text='Km o Horas al momento del servicio', null=True)),
                ('descripcion', models.TextField(help_text='Descripción del trabajo realizado o a realizar')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_refacciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='activos.activofijo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('programado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_programados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, help_text='Taller o proveedor que realizó el servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.proveedor')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
