# Generated by Django 6.0 on 2025-12-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago_secundario',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Crédito (Cuenta Corriente)'), ('ANTICIPO', 'Uso de Anticipo'), ('MIXTO', 'Mixto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_metodo_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_metodo_secundario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
