# Generated by Django 4.2.27 on 2025-12-28 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0002_venta_metodo_pago_secundario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('motivo', models.TextField(help_text='Motivo de la cancelación (requerido)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_autorizacion', models.TextField(blank=True, help_text='Comentarios del supervisor al aprobar/rechazar', null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('ip_solicitante', models.GenericIPAddressField(blank=True, help_text='IP desde donde se solicitó', null=True)),
                ('ip_autorizador', models.GenericIPAddressField(blank=True, help_text='IP desde donde se autorizó', null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, help_text='Supervisor que autorizó la cancelación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('solicitante', models.ForeignKey(help_text='Usuario que solicita la cancelación', on_delete=django.db.models.deletion.PROTECT, related_name='cancelaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cancelacion', to='pos.turno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cancelacion', to='pos.venta')),
            ],
            options={
                'verbose_name': 'Solicitud de Cancelación',
                'verbose_name_plural': 'Solicitudes de Cancelación',
                'ordering': ['-fecha_solicitud'],
                'permissions': [('open_cash_register', 'Abrir turno de caja'), ('close_cash_register', 'Cerrar turno de caja'), ('view_other_shifts', 'Ver turnos de otros cajeros'), ('modify_closed_shift', 'Modificar turnos cerrados'), ('view_all_sales', 'Ver ventas de todos los cajeros'), ('apply_discount', 'Aplicar descuentos a ventas'), ('apply_special_discount', 'Aplicar descuentos especiales (sin límite)'), ('sell_on_credit', 'Vender a crédito (cuenta corriente)'), ('sell_below_cost', 'Vender por debajo del precio de costo'), ('request_cancellation', 'Solicitar cancelación de ventas'), ('authorize_cancellation', 'Autorizar cancelaciones de ventas'), ('request_refund', 'Solicitar devoluciones de productos'), ('authorize_refund', 'Autorizar devoluciones de productos'), ('void_transaction', 'Anular transacciones del día'), ('manage_customer_credit', 'Gestionar crédito de clientes'), ('receive_payments', 'Recibir abonos de clientes'), ('adjust_customer_balance', 'Ajustar saldos de clientes manualmente'), ('register_cash_income', 'Registrar ingresos de efectivo'), ('register_cash_withdrawal', 'Registrar retiros de efectivo'), ('view_cash_movements', 'Ver movimientos de caja'), ('view_pos_reports', 'Ver reportes del punto de venta'), ('export_pos_reports', 'Exportar reportes del punto de venta'), ('view_sales_statistics', 'Ver estadísticas de ventas')],
            },
        ),
    ]
