# Generated by Django 6.0 on 2025-12-30 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_insumo_costo_promedio_insumo_ultimo_costo'),
        ('contabilidad', '0009_alter_certificadodigital_archivo_cer_and_more'),
        ('pos', '0003_solicitudcancelacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientocaja',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='movimientosaldocliente',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='fecha_fin',
            new_name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='cerrado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago_principal',
        ),
        migrations.AddField(
            model_name='caja',
            name='saldo_inicial_default',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo inicial sugerido para nuevos turnos', max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción snapshot del producto/insumo', max_length=200),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='insumo',
            field=models.ForeignKey(blank=True, help_text='Insumo del módulo de inventarios', null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.insumo'),
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ARQUEADA', 'Arqueada')], default='ABIERTA', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Crédito (Cuenta Corriente)'), ('ANTICIPO', 'Uso de Anticipo'), ('MIXTO', 'Mixto')], default='EFECTIVO', help_text='Método de pago principal', max_length=20),
        ),
        migrations.AlterField(
            model_name='caja',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto del catálogo POS (legacy)', null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='solicitudcancelacion',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, help_text='Supervisor que autorizó la cancelación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_autorizadas_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudcancelacion',
            name='ip_autorizador',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcancelacion',
            name='ip_solicitante',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcancelacion',
            name='solicitante',
            field=models.ForeignKey(help_text='Usuario que solicita la cancelación', on_delete=django.db.models.deletion.PROTECT, related_name='cancelaciones_solicitadas_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='pos.caja'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='saldo_final_calculado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que el sistema calcula', max_digits=12),
        ),
        migrations.AlterField(
            model_name='turno',
            name='saldo_final_declarado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que el cajero contó físicamente', max_digits=12),
        ),
        migrations.AlterField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_canceladas_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente opcional, null para venta general', null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago_secundario',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Crédito (Cuenta Corriente)'), ('ANTICIPO', 'Uso de Anticipo'), ('MIXTO', 'Mixto')], max_length=20, null=True),
        ),
    ]
