# Generated by Django 6.0 on 2026-01-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_movimientocaja_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clave_sat_producto',
            field=models.CharField(blank=True, help_text='Clave ProdServ SAT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='clave_sat_unidad',
            field=models.CharField(blank=True, help_text='Clave Unidad SAT', max_length=20, null=True),
        ),
    ]
