# Generated by Django 6.0 on 2026-01-03 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('titulo', models.CharField(help_text='Nombre de la plantilla', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido HTML de la plantilla. Usa {{variable}} para campos dinámicos')),
                ('tipo', models.CharField(choices=[('CONTRATO_TRABAJO', 'Contrato de Trabajo'), ('CONTRATO_SERVICIOS', 'Contrato de Servicios'), ('NDA', 'Acuerdo de Confidencialidad'), ('FINIQUITO', 'Finiquito'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Solo plantillas activas pueden usarse para generar documentos')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del uso de esta plantilla')),
                ('variables_disponibles', models.JSONField(blank=True, default=dict, help_text='Lista de variables disponibles para esta plantilla')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Plantilla Legal',
                'verbose_name_plural': 'Plantillas Legales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('object_id', models.PositiveIntegerField(help_text='ID del objeto vinculado')),
                ('archivo_pdf', models.FileField(help_text='PDF del documento firmado', upload_to='documentos_legales/%Y/%m/')),
                ('hash_firma', models.CharField(help_text='Hash SHA256 del documento para verificación de integridad', max_length=64, unique=True)),
                ('datos_firma', models.JSONField(default=dict, help_text='Metadatos de la firma: IP, UserAgent, Fecha, etc.')),
                ('fecha_firma', models.DateTimeField(blank=True, help_text='Fecha y hora de la firma', null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('datos_renderizados', models.JSONField(default=dict, help_text='Datos usados para renderizar la plantilla')),
                ('content_type', models.ForeignKey(help_text='Tipo de objeto vinculado (Empleado, Proveedor, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('usuario_firmante', models.ForeignKey(help_text='Usuario que firmó el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_firmados', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(help_text='Plantilla usada para generar este documento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='juridico.plantillalegal')),
            ],
            options={
                'verbose_name': 'Documento Firmado',
                'verbose_name_plural': 'Documentos Firmados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='juridico_do_content_721789_idx'), models.Index(fields=['estado'], name='juridico_do_estado_6a26c1_idx'), models.Index(fields=['hash_firma'], name='juridico_do_hash_fi_5d2e28_idx')],
            },
        ),
    ]
