# Generated by Django 6.0 on 2026-01-03 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Obra')),
                ('codigo', models.SlugField(unique=True, verbose_name='Código')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('presupuesto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Presupuesto Total')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(default=0)),
                ('es_hoja', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcentros', to='obras.centrocosto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_costo', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costos',
                'unique_together': {('obra', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PartidaPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.CharField(choices=[('MATERIALES', 'Materiales'), ('MANO_OBRA', 'Mano de Obra'), ('MAQUINARIA', 'Maquinaria'), ('INDIRECTOS', 'Indirectos'), ('SUBCONTRATOS', 'Subcontratos')], max_length=20)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_comprometido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='obras.centrocosto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Partida Presupuestal',
                'verbose_name_plural': 'Partidas Presupuestales',
            },
        ),
    ]
