# Generated by Django 6.0 on 2026-01-04 03:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_obra_empresa'),
        ('rrhh', '0014_nominacentralizada_fecha_timbrado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='porcentaje_anticipo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de Amortización por estimación', max_digits=5),
        ),
        migrations.AddField(
            model_name='obra',
            name='porcentaje_fondo_garantia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de Retención por garantía', max_digits=5),
        ),
        migrations.AddField(
            model_name='partidapresupuestal',
            name='monto_aditivas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aumentos autorizados al presupuesto', max_digits=14),
        ),
        migrations.CreateModel(
            name='ActividadProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(help_text='Código WBS o identificador único', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio_planeada', models.DateField()),
                ('fecha_fin_planeada', models.DateField()),
                ('duracion_dias', models.IntegerField(help_text='Duración estimada en días')),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('early_start', models.IntegerField(blank=True, help_text='Inicio más temprano (día)', null=True)),
                ('early_finish', models.IntegerField(blank=True, help_text='Fin más temprano (día)', null=True)),
                ('late_start', models.IntegerField(blank=True, help_text='Inicio más tardío (día)', null=True)),
                ('late_finish', models.IntegerField(blank=True, help_text='Fin más tardío (día)', null=True)),
                ('holgura', models.IntegerField(blank=True, help_text='Slack/Float en días', null=True)),
                ('es_critica', models.BooleanField(default=False, help_text='Actividad en ruta crítica')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='obras.obra')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_asignadas', to='rrhh.empleado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Actividad de Proyecto',
                'verbose_name_plural': 'Actividades de Proyecto',
                'ordering': ['obra', 'fecha_inicio_planeada'],
                'unique_together': {('obra', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Estimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_corte', models.DateField()),
                ('monto_avance', models.DecimalField(decimal_places=2, help_text='Monto bruto de trabajos ejecutados', max_digits=14)),
                ('amortizacion_anticipo', models.DecimalField(decimal_places=2, default=0, help_text='Deducción por anticipo', max_digits=14)),
                ('fondo_garantia', models.DecimalField(decimal_places=2, default=0, help_text='Deducción por garantía', max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Avance - Deducciones', max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, help_text='Neto a cobrar', max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADA', 'Autorizada'), ('FACTURADA', 'Facturada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimaciones', to='obras.obra')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DependenciaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], default='FS', max_length=2)),
                ('lag_dias', models.IntegerField(default=0, help_text='Retraso o adelanto en días (+ o -)')),
                ('actividad_predecesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesoras', to='obras.actividadproyecto')),
                ('actividad_sucesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecesoras', to='obras.actividadproyecto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Dependencia de Actividad',
                'verbose_name_plural': 'Dependencias de Actividades',
                'unique_together': {('actividad_predecesora', 'actividad_sucesora')},
            },
        ),
    ]
