# Generated by Django 6.0 on 2026-01-04 03:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('obras', '0003_obra_porcentaje_anticipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('PLANEACION', 'En Planeación'), ('EJECUCION', 'En Ejecución'), ('SUSPENDIDA', 'Suspendida'), ('LIQUIDACION', 'En Liquidación'), ('CERRADA', 'Cerrada')], default='PLANEACION', max_length=20),
        ),
        migrations.CreateModel(
            name='AsignacionRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_recurso', models.CharField(choices=[('LABOR', 'Mano de Obra'), ('EQUIPO', 'Maquinaria y Equipo'), ('MATERIAL', 'Insumos/Materiales')], max_length=20)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('porcentaje_dedicacion', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='obras.actividadproyecto')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Asignación de Recurso',
                'verbose_name_plural': 'Asignaciones de Recursos',
            },
        ),
        migrations.CreateModel(
            name='OrdenCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('ADITIVA', 'Aditiva (+ Presupuesto)'), ('DEDUCTIVA', 'Deductiva (- Presupuesto)'), ('REPROGRAMACION', 'Reprogramación (+/- Tiempo)')], max_length=20)),
                ('justificacion', models.TextField()),
                ('monto_impacto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dias_impacto', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('REVISADA', 'Revisada'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='SOLICITADA', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.actividadproyecto')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_cambio_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_cambio', to='obras.obra')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.partidapresupuestal')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_cambio_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Orden de Cambio',
                'verbose_name_plural': 'Ordenes de Cambio',
            },
        ),
    ]
