# Generated by Django 5.2.4 on 2025-08-02 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("clave", models.CharField(max_length=20, unique=True)),
                ("nombre_corto", models.CharField(max_length=100)),
                ("razon_social", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_completo", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("codigo", models.CharField(max_length=3, unique=True)),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Shark Tower", max_length=100, unique=True
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("numero_upes", models.PositiveIntegerField(default=0)),
                ("niveles", models.PositiveIntegerField(default=0)),
                (
                    "metros_cuadrados",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("numero_estacionamientos", models.PositiveIntegerField(default=0)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("estado", models.CharField(default="Planificado", max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "concepto",
                    models.CharField(
                        choices=[
                            ("APARTADO", "APARTADO"),
                            ("DEVOLUCIÓN", "DEVOLUCIÓN"),
                            ("DESCUENTO", "DESCUENTO"),
                            ("PAGO", "PAGO"),
                            ("MENSUALIDAD", "MENSUALIDAD"),
                        ],
                        default="PAGO",
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "banco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos",
                        to="cxc.banco",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="cxc.proyecto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Puesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puestos",
                        to="cxc.departamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="cxc.departamento",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="cxc.puesto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UPE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("identificador", models.CharField(max_length=100, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("Vendida", "Vendida"),
                            ("Pagada", "Pagada y Entregada"),
                            ("Bloqueada", "Bloqueada"),
                        ],
                        default="Disponible",
                        max_length=20,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upes",
                        to="cxc.proyecto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
