# Generated by Django 5.2.3 on 2025-07-16 17:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Shark Tower', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Liquidado', 'Liquidado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20)),
                ('precio_final_pactado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda_pactada', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], max_length=3)),
                ('monto_enganche', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_mensualidades', models.IntegerField(default=0)),
                ('tasa_interes_mensual', models.DecimalField(decimal_places=4, default=0.03, help_text='Ej: 0.03 para 3%', max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='cxc.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('ABONO', 'Abono a Capital'), ('INTERES', 'Pago de Intereses'), ('COMPLETO', 'Pago Completo')], default='ABONO', help_text='Concepto del pago (mapea a CONCEPTO)', max_length=50)),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Monto real de la transacción (mapea a PAGOS/ABONOS)', max_digits=12)),
                ('moneda_pagada', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], help_text='Mapea a DIVISA', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, help_text='Mapea a TIPO_CAMBIO', max_digits=10)),
                ('fecha_pago', models.DateField(default=datetime.date.today, help_text='Fecha en que se realizó el pago (mapea a FECHA_PAGO)')),
                ('fecha_ingreso_cuentas', models.DateField(blank=True, help_text='Fecha en que el dinero ingresó a cuentas', null=True)),
                ('instrumento_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'EFECTIVO'), ('TARJETA DE CRÉDITO', 'TARJETA DE CRÉDITO'), ('TARJETA DE DÉBITO', 'TARJETA DE DÉBITO'), ('TARJETA DE PREPAGO', 'TARJETA DE PREPAGO'), ('CHEQUE NOMINATIVO', 'CHEQUE NOMINATIVO'), ('CHEQUE DE CAJA', 'CHEQUE DE CAJA'), ('CHEQUE DE VIAJERO', 'CHEQUE DE VIAJERO'), ('TRANSFERENCIA INTERBANCARIA', 'TRANSFERENCIA INTERBANCARIA'), ('TRANSFERENCIA MISMA INSTITUCION', 'TRANSFERENCIA MISMA INSTITUCION'), ('TRANSFERENCIA INTERNACIONAL', 'TRANSFERENCIA INTERNACIONAL'), ('ORDEN DE PAGO', 'ORDEN DE PAGO'), ('GIRO', 'GIRO'), ('ORO O PLATINO AMONEDADOS', 'ORO O PLATINO AMONEDADOS'), ('PLATA AMONEDADA', 'PLATA AMONEDADA'), ('METALES PRECIOSO', 'METALES PRECIOSO')], help_text='Mapea a TIPO_PAGO (METODO DE PAGO)', max_length=100, null=True)),
                ('ordenante', models.CharField(blank=True, help_text='Persona o empresa que ordena el pago', max_length=200, null=True)),
                ('banco_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('num_cuenta_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('banco_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta_beneficiaria', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cxc.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDePagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('monto_programado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('ENGANCHE', 'Enganche'), ('MENSUALIDAD', 'Mensualidad')], max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_de_pagos', to='cxc.contrato')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='UPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: Departamento 501, Lote 23', max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total de la unidad', max_digits=12)),
                ('moneda', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='USD', max_length=3)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendida', 'Vendida'), ('Pagada', 'Pagada y Entregada'), ('Bloqueada', 'Bloqueada')], default='Disponible', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upes', to='cxc.proyecto')),
            ],
            options={
                'unique_together': {('proyecto', 'identificador')},
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='upe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='cxc.upe'),
        ),
    ]
