# Generated by Django 5.2.4 on 2025-08-04 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre_corto', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('saldo_presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('abonado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_ultimo_abono', models.DateField(blank=True, null=True)),
                ('monto_ultimo_abono', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('monto_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EsquemaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('esquema', models.CharField(choices=[('RENTA', 'Renta'), ('VENTA', 'Venta')], max_length=10)),
                ('escenario', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=3, max_digits=6)),
                ('iva', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('enganche', models.PositiveSmallIntegerField()),
                ('mensualidades', models.PositiveSmallIntegerField()),
                ('meses', models.PositiveSmallIntegerField()),
                ('contra_entrega', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(choices=[('N/A', 'N/A'), ('EFECTIVO', 'EFECTIVO'), ('TARJETA_CREDITO', 'TARJETA DE CREDITO'), ('TARJETA_DEBITO', 'TARJETA DE DEBITO'), ('TARJETA_PREPAGO', 'TARJETA DE PREPAGO'), ('CHEQUE_NOMINATIVO', 'CHEQUE NOMINATIVO'), ('CHEQUE_CAJA', 'CHEQUE DE CAJA'), ('CHEQUE_VIAJERO', 'CHEQUE DE VIAJERO'), ('TRANSFERENCIA_INTERBANCARIA', 'TRANSFERENCIA INTERBANCARIA'), ('TRANSFERENCIA_MISMA_INSTITUCION', 'TRANSFERENCIA MISMA INSTITUCION'), ('TRANSFERENCIA_INTERNACIONAL', 'TRANSFERENCIA INTERNACIONAL'), ('ORDEN_PAGO', 'ORDEN DE PAGO'), ('GIRO', 'GIRO'), ('ORO_PLATINO', 'ORO O PLATINO AMONEDADOS'), ('PLATA', 'PLATA AMONEDADA'), ('METALES_PRECIOSOS', 'METALES PRECIOSO')], max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_pago', models.CharField(choices=[('APARTADO', 'Apartado'), ('DEVOLUCION', 'Devolución'), ('MENSUALIDAD', 'Mensualidad'), ('PAGO', 'Pago'), ('DESCUENTO', 'Descuento')], max_length=20)),
                ('fecha_pago', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_mxn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuenta_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('titular_origen', models.CharField(blank=True, max_length=200, null=True)),
                ('cuenta_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('apartado_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_apartado', models.DateField(blank=True, null=True)),
                ('monto_enganche', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_enganche', models.DateField(blank=True, null=True)),
                ('monto_mensualidades', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('meses', models.PositiveSmallIntegerField(default=0)),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_contra_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('precio_m2', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_con_descuento', models.DecimalField(decimal_places=2, max_digits=14)),
                ('enganche', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_entrega_pactada', models.DateField(blank=True, null=True)),
                ('negociaciones_especiales', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_upes', models.PositiveIntegerField(default=0)),
                ('niveles', models.PositiveIntegerField(default=0)),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_estacionamientos', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(default='Planificado', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('escenario', models.CharField(choices=[('PACTADO', 'Pactado'), ('TOPADO', 'Topado'), ('BANXICO', 'Banxico')], max_length=20)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='UPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estacionamientos', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDIDA', 'Vendida'), ('PAGADA', 'Pagada'), ('BLOQUEADA', 'Bloqueada')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authy_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], max_length=10)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='cxc.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
