# Generated by Django 5.2.4 on 2025-08-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("TARJETA_DEBITO", "Tarjeta de Débito"),
                            ("TARJETA_CREDITO", "Tarjeta de Crédito"),
                            ("CHEQUE", "Cheque"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
