# Generated by Django 5.2.3 on 2025-07-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeCambio',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
