# Generated by Django 5.2.3 on 2025-07-01 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='notas',
            new_name='comentarios',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='banco_destino',
            field=models.CharField(blank=True, db_column='BANCO_DESTINO', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='banco_origen',
            field=models.CharField(blank=True, db_column='BANCO_ORIGEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_ingreso_cuentas',
            field=models.DateField(blank=True, help_text='Fecha en que el dinero ingresó a cuentas', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago_mensualidad',
            field=models.DateField(default=datetime.date(2025, 7, 1), help_text='Fecha de pago real o programada de la mensualidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='instrumento_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'EFECTIVO'), ('TARJETA DE CRÉDITO', 'TARJETA DE CRÉDITO'), ('TARJETA DE DÉBITO', 'TARJETA DE DÉBITO'), ('TARJETA DE PREPAGO', 'TARJETA DE PREPAGO'), ('CHEQUE NOMINATIVO', 'CHEQUE NOMINATIVO'), ('CHEQUE DE CAJA', 'CHEQUE DE CAJA'), ('CHEQUE DE VIAJERO', 'CHEQUE DE VIAJERO'), ('TRANSFERENCIA INTERBANCARIA', 'TRANSFERENCIA INTERBANCARIA'), ('TRANSFERENCIA MISMA INSTITUCION', 'TRANSFERENCIA MISMA INSTITUCION'), ('TRANSFERENCIA INTERNACIONAL', 'TRANSFERENCIA INTERNACIONAL'), ('ORDEN DE PAGO', 'ORDEN DE PAGO'), ('GIRO', 'GIRO'), ('ORO O PLATINO AMONEDADOS', 'ORO O PLATINO AMONEDADOS'), ('PLATA AMONEDADA', 'PLATA AMONEDADA'), ('METALES PRECIOSO', 'METALES PRECIOSO')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='num_cuenta_destino',
            field=models.CharField(blank=True, db_column='NUM_CUENTA_DESTINO', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='num_cuenta_origen',
            field=models.CharField(blank=True, db_column='NUM_CUENTA_ORIGEN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('MENSUALIDAD', 'Mensualidad'), ('ENGANCHE', 'Enganche'), ('PAGO FINAL', 'Pago Final'), ('OTRO', 'Otro')], default='MENSUALIDAD', help_text='Tipo de pago (ej. Mensualidad, Enganche)', max_length=50),
        ),
        migrations.AddField(
            model_name='pago',
            name='titular_cuenta_origen',
            field=models.CharField(blank=True, db_column='TITULAR_CUENTA_ORIGEN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
