# Generated by Django 5.2.4 on 2025-08-04 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cxc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxc.moneda'),
        ),
        migrations.AddField(
            model_name='pago',
            name='banco_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_destino', to='cxc.banco'),
        ),
        migrations.AddField(
            model_name='pago',
            name='banco_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_origen', to='cxc.banco'),
        ),
        migrations.AddField(
            model_name='pago',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cxc.contrato'),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxc.metodopago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxc.moneda'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='cxc.cliente'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='forma_pago_contra_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_contra_entrega', to='cxc.formapago'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='forma_pago_enganche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_enganche', to='cxc.formapago'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='forma_pago_mensualidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_mensualidades', to='cxc.formapago'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='forma_pago_meses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_meses', to='cxc.formapago'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='moneda_apartado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_apartado', to='cxc.moneda'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='moneda_contra_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_contra_entrega_moneda', to='cxc.moneda'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='moneda_enganche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_enganche_moneda', to='cxc.moneda'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='moneda_mensual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_mensual_moneda', to='cxc.moneda'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='moneda_mensualidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_mensualidades_moneda', to='cxc.moneda'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='cxc.cliente'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='empleado1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_empleado1', to='cxc.empleado'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='empleado2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_empleado2', to='cxc.empleado'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='empleado3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_empleado3', to='cxc.empleado'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='esquema_comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cxc.esquemacomision'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxc.formapago'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cxc.metodopago'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxc.moneda'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='plan_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='cxc.planpago'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='cxc.presupuesto'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='cxc.departamento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='cxc.puesto'),
        ),
        migrations.AlterUniqueTogether(
            name='tipocambio',
            unique_together={('escenario', 'fecha')},
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo_cambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxc.tipocambio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_cambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxc.tipocambio'),
        ),
        migrations.AddField(
            model_name='upe',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxc.moneda'),
        ),
        migrations.AddField(
            model_name='upe',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upes', to='cxc.proyecto'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='upe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='cxc.upe'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='upe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='cxc.upe'),
        ),
        migrations.AddField(
            model_name='usertwofactor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='vendedor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_vendedor1', to='cxc.vendedor'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='vendedor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_vendedor2', to='cxc.vendedor'),
        ),
    ]
