# Generated by Django 5.2.4 on 2025-08-02 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="pago",
            old_name="fecha",
            new_name="fecha_pago",
        ),
        migrations.RenameField(
            model_name="pago",
            old_name="monto",
            new_name="monto_pagado",
        ),
        migrations.AddField(
            model_name="pago",
            name="banco_destino",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="banco_origen",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="comentarios",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="cuenta_beneficiaria",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="moneda_pagada",
            field=models.CharField(default="MXN", max_length=3),
        ),
        migrations.AddField(
            model_name="pago",
            name="num_cuenta_origen",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="ordenante",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="tipo_cambio",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pago",
            name="valor_mxn",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_contrato", models.DateField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="cxc.cliente",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pago",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="cxc.contrato",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="metodo_pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos",
                to="cxc.metodopago",
            ),
        ),
    ]
