# Generated by Django 5.2.4 on 2025-08-02 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "monto_apartado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="cxc.cliente",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="cxc.proyecto",
                    ),
                ),
                (
                    "upe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="cxc.upe",
                    ),
                ),
            ],
            options={
                "unique_together": {("cliente", "upe")},
            },
        ),
    ]
