# Generated by Django 5.2.3 on 2025-07-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0002_tipodecambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(choices=[('APARTADO', 'APARTADO'), ('DEVOLUCIÓN', 'DEVOLUCIÓN'), ('DESCUENTO', 'DESCUENTO'), ('PAGO', 'PAGO')], default='ABONO', help_text='Concepto del pago (mapea a CONCEPTO)', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='instrumento_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'EFECTIVO'), ('TARJETA DE CREDITO', 'TARJETA DE CREDITO'), ('TARJETA DE DEBITO', 'TARJETA DE DEBITO'), ('TARJETA DE PREPAGO', 'TARJETA DE PREPAGO'), ('CHEQUE NOMINATIVO', 'CHEQUE NOMINATIVO'), ('CHEQUE DE CAJA', 'CHEQUE DE CAJA'), ('CHEQUE DE VIAJERO', 'CHEQUE DE VIAJERO'), ('TRANSFERENCIA INTERBANCARIA', 'TRANSFERENCIA INTERBANCARIA'), ('TRANSFERENCIA MISMA INSTITUCION', 'TRANSFERENCIA MISMA INSTITUCION'), ('TRANSFERENCIA INTERNACIONAL', 'TRANSFERENCIA INTERNACIONAL'), ('ORDEN DE PAGO', 'ORDEN DE PAGO'), ('GIRO', 'GIRO'), ('ORO O PLATINO AMONEDADOS', 'ORO O PLATINO AMONEDADOS'), ('PLATA AMONEDADA', 'PLATA AMONEDADA'), ('METALES PRECIOSO', 'METALES PRECIOSO')], help_text='Mapea a TIPO_PAGO (METODO DE PAGO)', max_length=100, null=True),
        ),
    ]
