# Generated by Django 5.2.4 on 2025-07-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0003_alter_pago_concepto_alter_pago_instrumento_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plandepagos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipodecambio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upe',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
