# Generated by Django 5.2.4 on 2025-07-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0008_translate_auth_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraPermission',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
