# Generated by Django 5.2.4 on 2025-08-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0009_delete_extrapermission_alter_auditlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsquemaComision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("esquema", models.CharField(max_length=100)),
                ("escenario", models.CharField(max_length=100)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                ("iva", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
