# Generated by Django 5.2.4 on 2025-08-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0009_delete_extrapermission_alter_auditlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("clave", models.CharField(max_length=20, unique=True)),
                ("nombre_corto", models.CharField(max_length=100)),
                ("razon_social", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(default="Planificado", max_length=50),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="metros_cuadrados",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="niveles",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="numero_estacionamientos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="numero_upes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="upe",
            name="estacionamientos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="upe",
            name="metros_cuadrados",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="upe",
            name="nivel",
            field=models.IntegerField(default=0),
        ),
    ]
