# Generated by Django 5.2.4 on 2025-08-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0009_delete_extrapermission_alter_auditlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("codigo", models.CharField(max_length=3, unique=True)),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="contrato",
            name="moneda_pactada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cxc.moneda",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="moneda_pagada",
            field=models.ForeignKey(
                blank=True,
                help_text="Mapea a DIVISA",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cxc.moneda",
            ),
        ),
        migrations.AlterField(
            model_name="upe",
            name="moneda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cxc.moneda",
            ),
        ),
        migrations.RunPython(lambda apps, schema_editor: (
            apps.get_model('cxc', 'Moneda').objects.get_or_create(codigo='MXN', defaults={'nombre': 'MXN'}),
            apps.get_model('cxc', 'Moneda').objects.get_or_create(codigo='USD', defaults={'nombre': 'USD'})
        )),
    ]
