# Generated by Django 5.2.4 on 2025-08-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0009_delete_extrapermission_alter_auditlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("escenario", models.CharField(max_length=50)),
                ("fecha", models.DateField()),
                ("valor", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                "ordering": ["-fecha"],
                "unique_together": {("escenario", "fecha")},
            },
        ),
    ]
