# Generated by Django 5.2.4 on 2025-08-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0009_delete_extrapermission_alter_auditlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormaPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "porcentajes",
                    models.JSONField(help_text="Lista de porcentajes de cada pago"),
                ),
                (
                    "meses",
                    models.JSONField(help_text="Meses correspondientes a cada pago"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
