# Generated by Django 5.2.4 on 2025-08-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0009_delete_extrapermission_alter_auditlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "monto_programado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monto_pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("fecha_programada", models.DateField()),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("MXN", "MXN"), ("USD", "USD")], max_length=3
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("TARJETA", "Tarjeta"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_pago",
                        to="cxc.cliente",
                    ),
                ),
                (
                    "upe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_pago",
                        to="cxc.upe",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_programada"],
            },
        ),
    ]
