# Generated by Django 5.2.4 on 2025-08-01 22:23

import django.db.models.deletion
from django.db import migrations, models


def seed_metodos_pago(apps, schema_editor):
    MetodoPago = apps.get_model('cxc', 'MetodoPago')
    Pago = apps.get_model('cxc', 'Pago')

    opciones = [
        'EFECTIVO', 'TARJETA DE CREDITO', 'TARJETA DE DEBITO',
        'TARJETA DE PREPAGO', 'CHEQUE NOMINATIVO', 'CHEQUE DE CAJA',
        'CHEQUE DE VIAJERO', 'TRANSFERENCIA INTERBANCARIA',
        'TRANSFERENCIA MISMA INSTITUCION', 'TRANSFERENCIA INTERNACIONAL',
        'ORDEN DE PAGO', 'GIRO', 'ORO O PLATINO AMONEDADOS',
        'PLATA AMONEDADA', 'METALES PRECIOSO',
    ]
    for nombre in opciones:
        MetodoPago.objects.create(nombre=nombre)

    for pago in Pago.objects.all():
        if getattr(pago, 'instrumento_pago', None):
            metodo = MetodoPago.objects.filter(nombre=pago.instrumento_pago).first()
            pago.metodo_pago = metodo
            pago.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cxc", "0009_delete_extrapermission_alter_auditlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="pago",
            name="metodo_pago",
            field=models.ForeignKey(
                blank=True,
                help_text="Mapea a TIPO_PAGO (METODO DE PAGO)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="cxc.metodopago",
            ),
        ),
        migrations.RunPython(seed_metodos_pago, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="pago",
            name="instrumento_pago",
        ),
    ]
