# Generated by Django 6.0 on 2025-12-16 18:32

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_upes', models.PositiveIntegerField(default=0)),
                ('niveles', models.PositiveIntegerField(default=0)),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_estacionamientos', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(default='Planificado', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('escenario', models.CharField(choices=[('PACTADO', 'Pactado'), ('TOPADO', 'Topado'), ('BANXICO', 'Banxico')], max_length=20)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='UPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estacionamientos', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDIDA', 'Vendida'), ('PAGADA', 'Pagada'), ('BLOQUEADA', 'Bloqueada')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'permissions': [('can_use_ai', 'Can Use AI Chat')],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], max_length=10)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre_corto', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EsquemaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('esquema', models.CharField(choices=[('RENTA', 'Renta'), ('VENTA', 'Venta')], max_length=10)),
                ('escenario', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=3, max_digits=6)),
                ('iva', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('enganche', models.PositiveSmallIntegerField()),
                ('mensualidades', models.PositiveSmallIntegerField()),
                ('meses', models.PositiveSmallIntegerField()),
                ('contra_entrega', models.PositiveSmallIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(choices=[('N/A', 'N/A'), ('EFECTIVO', 'EFECTIVO'), ('TARJETA_CREDITO', 'TARJETA DE CREDITO'), ('TARJETA_DEBITO', 'TARJETA DE DEBITO'), ('TARJETA_PREPAGO', 'TARJETA DE PREPAGO'), ('CHEQUE_NOMINATIVO', 'CHEQUE NOMINATIVO'), ('CHEQUE_CAJA', 'CHEQUE DE CAJA'), ('CHEQUE_VIAJERO', 'CHEQUE DE VIAJERO'), ('TRANSFERENCIA_INTERBANCARIA', 'TRANSFERENCIA INTERBANCARIA'), ('TRANSFERENCIA_MISMA_INSTITUCION', 'TRANSFERENCIA MISMA INSTITUCION'), ('TRANSFERENCIA_INTERNACIONAL', 'TRANSFERENCIA INTERNACIONAL'), ('ORDEN_PAGO', 'ORDEN DE PAGO'), ('GIRO', 'GIRO'), ('ORO_PLATINO', 'ORO O PLATINO AMONEDADOS'), ('PLATA', 'PLATA AMONEDADA'), ('METALES_PRECIOSOS', 'METALES PRECIOSO')], max_length=40, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('saldo_presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('abonado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_ultimo_abono', models.DateField(blank=True, null=True)),
                ('monto_ultimo_abono', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('monto_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.moneda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_pago', models.CharField(choices=[('APARTADO', 'Apartado'), ('DEVOLUCION', 'Devolución'), ('MENSUALIDAD', 'Mensualidad'), ('PAGO', 'Pago'), ('DESCUENTO', 'Descuento'), ('ABONO', 'Abono'), ('INTERES', 'Interés'), ('COMPLETO', 'Completo')], max_length=20)),
                ('fecha_pago', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_mxn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuenta_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('titular_origen', models.CharField(blank=True, max_length=200, null=True)),
                ('cuenta_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('banco_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_destino', to='contabilidad.banco')),
                ('banco_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_origen', to='contabilidad.banco')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='contabilidad.contrato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.metodopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.moneda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('apartado_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_apartado', models.DateField(blank=True, null=True)),
                ('monto_enganche', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_enganche', models.DateField(blank=True, null=True)),
                ('monto_mensualidades', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('meses', models.PositiveSmallIntegerField(default=0)),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_contra_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='contabilidad.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('forma_pago_contra_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_contra_entrega', to='contabilidad.formapago')),
                ('forma_pago_enganche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_enganche', to='contabilidad.formapago')),
                ('forma_pago_mensualidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_mensualidades', to='contabilidad.formapago')),
                ('forma_pago_meses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_meses', to='contabilidad.formapago')),
                ('moneda_apartado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_apartado', to='contabilidad.moneda')),
                ('moneda_contra_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_contra_entrega_moneda', to='contabilidad.moneda')),
                ('moneda_enganche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_enganche_moneda', to='contabilidad.moneda')),
                ('moneda_mensual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_mensual_moneda', to='contabilidad.moneda')),
                ('moneda_mensualidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_mensualidades_moneda', to='contabilidad.moneda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('precio_m2', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_con_descuento', models.DecimalField(decimal_places=2, max_digits=14)),
                ('enganche', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_entrega_pactada', models.DateField(blank=True, null=True)),
                ('negociaciones_especiales', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='contabilidad.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
