# Generated by Django 6.0 on 2025-12-16 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='empleado1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_empleado1', to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='empleado2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_empleado2', to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='empleado3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_empleado3', to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='esquema_comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.esquemacomision'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.formapago'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.metodopago'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.moneda'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='plan_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='contabilidad.planpago'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='contabilidad.presupuesto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo_cambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.tipocambio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_cambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.tipocambio'),
        ),
        migrations.AddField(
            model_name='upe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='upe',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.moneda'),
        ),
        migrations.AddField(
            model_name='upe',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upes', to='contabilidad.proyecto'),
        ),
        migrations.AddField(
            model_name='upe',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='upe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upes_presupuesto', related_query_name='presupuesto', to='contabilidad.upe'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='upe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='contabilidad.upe'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='vendedor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_vendedor1', to='contabilidad.vendedor'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='vendedor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_vendedor2', to='contabilidad.vendedor'),
        ),
        migrations.AlterUniqueTogether(
            name='tipocambio',
            unique_together={('escenario', 'fecha')},
        ),
    ]
