# Generated by Django 6.0 on 2025-12-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentEmbedding',
        ),
    ]
