# Generated by Django 6.0 on 2025-12-24 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_centrocostos_cuentacontable_poliza_detallepoliza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('version', models.CharField(default='4.0', max_length=5)),
                ('uuid', models.CharField(blank=True, help_text='Folio Fiscal (UUID) del SAT', max_length=36, null=True, unique=True)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('folio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('emisor_rfc', models.CharField(max_length=13)),
                ('emisor_nombre', models.CharField(max_length=255)),
                ('emisor_regimen', models.CharField(blank=True, max_length=10, null=True)),
                ('receptor_rfc', models.CharField(max_length=13)),
                ('receptor_nombre', models.CharField(max_length=255)),
                ('receptor_regimen', models.CharField(blank=True, max_length=10, null=True)),
                ('uso_cfdi', models.CharField(blank=True, max_length=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos_trasladados', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos_retenidos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('tipo_comprobante', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('P', 'Pago'), ('N', 'Nómina'), ('T', 'Traslado')], default='I', max_length=1)),
                ('estado_sat', models.CharField(choices=[('VIGENTE', 'Vigente'), ('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente de Timbrado')], default='VIGENTE', max_length=20)),
                ('xml_archivo', models.FileField(blank=True, null=True, upload_to='facturas/xml/%Y/%m/')),
                ('pdf_archivo', models.FileField(blank=True, null=True, upload_to='facturas/pdf/%Y/%m/')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='contabilidad.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.formapago')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.metodopago')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.moneda')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='contabilidad.proyecto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
