# Generated by Django 6.0 on 2025-12-27 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_factura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='tipo_operacion',
            field=models.CharField(choices=[('03', '03 - Prestación de Servicios Profesionales'), ('06', '06 - Arrendamiento de Inmuebles'), ('85', '85 - Otros')], default='85', max_length=2),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='tipo_tercero',
            field=models.CharField(choices=[('04', '04 - Proveedor Nacional'), ('05', '05 - Proveedor Extranjero'), ('15', '15 - Proveedor Global')], default='04', max_length=2),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='tipo',
            field=models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], default='EXTERNO', max_length=10),
        ),
        migrations.CreateModel(
            name='BuzonMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('rfc', models.CharField(max_length=13)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('fecha_recibido', models.DateTimeField()),
                ('leido', models.BooleanField(default=False)),
                ('es_requerimiento', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(help_text='Ej. CSD Principal 2024', max_length=100)),
                ('rfc', models.CharField(help_text='RFC al que pertenece el certificado', max_length=13)),
                ('tipo', models.CharField(choices=[('FIEL', 'Firma Electrónica (FIEL)'), ('CSD', 'Certificado de Sello Digital (CSD)')], default='CSD', max_length=10)),
                ('archivo_cer', models.FileField(help_text='Archivo .cer (Público)', upload_to='sat/certs/')),
                ('archivo_key', models.FileField(help_text='Archivo .key (Privado) - Proteger acceso', upload_to='sat/keys/')),
                ('password', models.CharField(help_text='Contraseña de la clave privada (Encriptada)', max_length=255)),
                ('fecha_inicio_validez', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_validez', models.DateTimeField(blank=True, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionCumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('rfc', models.CharField(max_length=13)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('POSITIVA', 'Positiva'), ('NEGATIVA', 'Negativa'), ('SIN_OBLIGACIONES', 'Sin Obligaciones')], max_length=20)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='sat/opiniones/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantillaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_poliza', models.CharField(choices=[('PROVISION', 'Provisión (Diario)'), ('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso (Pago)')], max_length=20)),
                ('concepto_patron', models.CharField(help_text='Ej: Provisión Fac. {serie}-{folio} {receptor}', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReglaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_movimiento', models.CharField(choices=[('CARGO', 'Cargo'), ('ABONO', 'Abono')], max_length=10)),
                ('origen_dato', models.CharField(choices=[('SUBTOTAL', 'Subtotal'), ('TOTAL', 'Total (Neto)'), ('IVA_16', 'IVA 16%'), ('IVA_RET', 'IVA Retenido'), ('ISR_RET', 'ISR Retenido'), ('IEPS', 'IEPS'), ('FIJO', 'Monto Fijo (Manual)')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuenta_base', models.ForeignKey(help_text='Cuenta default', on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='contabilidad.plantillaasiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
