# Generated by Django 6.0 on 2025-12-27 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_vendedor_rfc_vendedor_tipo_operacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipocambio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='moneda_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_cambio_destino', to='contabilidad.moneda'),
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='moneda_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_cambio_origen', to='contabilidad.moneda'),
        ),
        migrations.AlterUniqueTogether(
            name='tipocambio',
            unique_together={('escenario', 'fecha', 'moneda_origen', 'moneda_destino')},
        ),
    ]
