# Generated by Django 4.2.27 on 2025-12-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_tipocambio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upe',
            options={'permissions': [('manage_chart_of_accounts', 'Gestionar catálogo de cuentas contables'), ('close_accounting_period', 'Cerrar períodos contables'), ('create_journal_entry', 'Crear pólizas contables'), ('post_journal_entry', 'Aplicar/Mayorizar pólizas'), ('reverse_journal_entry', 'Revertir pólizas aplicadas'), ('delete_journal_entry', 'Eliminar pólizas contables'), ('issue_invoice', 'Emitir facturas (CFDI)'), ('cancel_invoice', 'Cancelar facturas (CFDI)'), ('view_fiscal_documents', 'Ver documentos fiscales'), ('manage_exchange_rates', 'Gestionar tipos de cambio'), ('view_financial_statements', 'Ver estados financieros'), ('export_financial_reports', 'Exportar reportes financieros'), ('view_diot', 'Ver DIOT'), ('generate_diot', 'Generar DIOT'), ('use_ai_accounting', 'Usar IA para contabilidad')]},
        ),
    ]
