# Generated by Django 6.0 on 2025-12-30 19:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_alter_upe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadodigital',
            name='archivo_cer',
            field=models.FileField(help_text='Archivo .cer (Público)', storage=django.core.files.storage.FileSystemStorage(location='/app/core/certificates'), upload_to='certs/'),
        ),
        migrations.AlterField(
            model_name='certificadodigital',
            name='archivo_key',
            field=models.FileField(help_text='Archivo .key (Privado) - Proteger acceso', storage=django.core.files.storage.FileSystemStorage(location='/app/core/certificates'), upload_to='keys/'),
        ),
    ]
