# Generated by Django 6.0 on 2026-01-03 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_alter_certificadodigital_archivo_cer_and_more'),
        ('core', '0002_featureflag_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SATFormaPago',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('bancarizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SATMetodoPago',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SATRegimenFiscal',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fisica', models.BooleanField(default=False)),
                ('moral', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SATUsoCFDI',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fisica', models.BooleanField(default=False)),
                ('moral', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificadodigital',
            name='password',
        ),
        migrations.AddField(
            model_name='certificadodigital',
            name='password_key',
            field=models.CharField(default='default', help_text='Contraseña de la clave privada (Encriptada)', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, help_text='Para facturación', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='certificadodigital',
            name='archivo_key',
            field=models.BinaryField(help_text='Archivo .key (Privado) ENCRIPTADO'),
        ),
        migrations.CreateModel(
            name='EmpresaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo_postal', models.CharField(help_text='Lugar de expedición', max_length=5)),
                ('certificado_sello', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_asociada', to='contabilidad.certificadodigital')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_fiscal', to='core.empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('regimen_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.satregimenfiscal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.satregimenfiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uso_cfdi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.satusocfdi'),
        ),
    ]
