# Generated by Django 6.0 on 2026-01-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_satformapago_satmetodopago_satregimenfiscal_and_more'),
        ('pos', '0005_producto_clave_sat_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='pos.venta'),
        ),
    ]
