# Generated by Django 6.0 on 2026-01-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_factura_venta'),
        ('core', '0002_featureflag_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
    ]
