# Generated by Django 6.0 on 2026-01-04 04:22
# Modified manually to create only CFDI tables

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('contabilidad', '0012_factura_empresa'),
    ]

    operations = [
        # Create CFDI Catalog Tables
        migrations.CreateModel(
            name='CFDIClaveProdServ',
            fields=[
                ('clave', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('incluye_iva', models.BooleanField(default=True)),
                ('incluye_ieps', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Clave Producto/Servicio CFDI',
                'verbose_name_plural': 'Claves Productos/Servicios CFDI',
                'db_table': 'cfdi_clave_prod_serv',
            },
        ),
        migrations.CreateModel(
            name='CFDIUnidad',
            fields=[
                ('clave', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida CFDI',
                'verbose_name_plural': 'Unidades de Medida CFDI',
                'db_table': 'cfdi_unidad',
            },
        ),
        migrations.CreateModel(
            name='CFDIFormaPago',
            fields=[
                ('clave', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Forma de Pago CFDI',
                'verbose_name_plural': 'Formas de Pago CFDI',
                'db_table': 'cfdi_forma_pago',
            },
        ),
        migrations.CreateModel(
            name='CFDIMetodoPago',
            fields=[
                ('clave', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Método de Pago CFDI',
                'verbose_name_plural': 'Métodos de Pago CFDI',
                'db_table': 'cfdi_metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='CFDIUsoCFDI',
            fields=[
                ('clave', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('aplica_persona_fisica', models.BooleanField(default=True)),
                ('aplica_persona_moral', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Uso de CFDI',
                'verbose_name_plural': 'Usos de CFDI',
                'db_table': 'cfdi_uso_cfdi',
            },
        ),
        # Create CertificadoDigital (updated model)
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_certificado', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('archivo_cer', models.FileField(help_text='Archivo .cer del SAT', upload_to='certificados/cer/')),
                ('archivo_key', models.FileField(help_text='Archivo .key del SAT', upload_to='certificados/key/')),
                ('password_key', models.CharField(help_text='Contraseña encriptada con Fernet', max_length=255)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('rfc_titular', models.CharField(blank=True, max_length=13, null=True)),
                ('razon_social_titular', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_digitales', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Certificado Digital (CSD)',
                'verbose_name_plural': 'Certificados Digitales',
                'ordering': ['-fecha_fin'],
            },
        ),
        # Create Factura (new CFDI model)
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(db_index=True, max_length=20)),
                ('serie', models.CharField(blank=True, default='A', max_length=10)),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Folio Fiscal (UUID)')),
                ('tipo_comprobante', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('T', 'Traslado'), ('N', 'Nómina'), ('P', 'Pago')], default='I', max_length=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('lugar_expedicion', models.CharField(blank=True, help_text='Código Postal de expedición', max_length=5, null=True)),
                ('condiciones_pago', models.CharField(blank=True, help_text='Ej: Pago a 30 días', max_length=200)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('xml_original', models.TextField(blank=True, help_text='XML antes de timbrar')),
                ('xml_timbrado', models.TextField(blank=True, help_text='XML con UUID del PAC')),
                ('cadena_original', models.TextField(blank=True)),
                ('sello_digital', models.TextField(blank=True)),
                ('sello_sat', models.TextField(blank=True)),
                ('numero_certificado_sat', models.CharField(blank=True, max_length=20)),
                ('fecha_certificacion_sat', models.DateTimeField(blank=True, null=True)),
                ('pdf_archivo', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('TIMBRADA', 'Timbrada'), ('CANCELADA', 'Cancelada'), ('ERROR', 'Error de Timbrado')], db_index=True, default='BORRADOR', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('uuid_sustitucion', models.UUIDField(blank=True, help_text='UUID de factura que sustituye a esta', null=True)),
                ('correo_enviado', models.BooleanField(default=False)),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_cfdi', to='core.empresa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cfdi', to='contabilidad.cliente')),
                ('forma_pago', models.ForeignKey(help_text='Ej: 03-Transferencia', on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cfdiformapago')),
                ('metodo_pago', models.ForeignKey(help_text='PUE o PPD', on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cfdimetodopago')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura Electrónica (CFDI)',
                'verbose_name_plural': 'Facturas Electrónicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['uuid'], name='contabilida_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado', 'fecha'], name='contabilida_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente', 'fecha'], name='contabilida_cliente_fecha_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('empresa', 'serie', 'folio')},
        ),
        # Create ConceptoFactura
        migrations.CreateModel(
            name='ConceptoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.IntegerField()),
                ('no_identificacion', models.CharField(blank=True, help_text='SKU o código interno', max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=6, max_digits=16)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=16)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('objeto_imp', models.CharField(default='02', help_text='01=No objeto, 02=Sí objeto, 03=Sí objeto no obligado', max_length=2)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='contabilidad.factura')),
                ('clave_prod_serv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cfdiclaveprodserv', verbose_name='Clave Producto/Servicio SAT')),
                ('clave_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cfdiunidad', verbose_name='Unidad de Medida SAT')),
            ],
            options={
                'verbose_name': 'Concepto de Factura',
                'verbose_name_plural': 'Conceptos de Factura',
                'ordering': ['numero_linea'],
            },
        ),
        # Create ImpuestoConcepto
        migrations.CreateModel(
            name='ImpuestoConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRASLADO', 'Traslado'), ('RETENCION', 'Retención')], max_length=10)),
                ('impuesto', models.CharField(help_text='002=IVA, 001=ISR, 003=IEPS', max_length=3)),
                ('tipo_factor', models.CharField(choices=[('Tasa', 'Tasa'), ('Cuota', 'Cuota'), ('Exento', 'Exento')], default='Tasa', max_length=10)),
                ('tasa_o_cuota', models.DecimalField(decimal_places=6, help_text='Ej: 0.160000 para IVA 16%', max_digits=8)),
                ('base', models.DecimalField(decimal_places=2, max_digits=16)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=16)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='contabilidad.conceptofactura')),
            ],
            options={
                'verbose_name': 'Impuesto de Concepto',
                'verbose_name_plural': 'Impuestos de Conceptos',
            },
        ),
    ]
