# Generated by Django 6.0 on 2026-01-04 04:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_add_cfdi_models'),
        ('core', '0002_featureflag_systemsetting'),
        ('obras', '0004_obra_estado_asignacionrecurso_ordencambio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satformapago',
            options={'verbose_name': 'Forma de Pago SAT (Legacy)', 'verbose_name_plural': 'Formas de Pago SAT (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='satmetodopago',
            options={'verbose_name': 'Método de Pago SAT (Legacy)', 'verbose_name_plural': 'Métodos de Pago SAT (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='satregimenfiscal',
            options={'verbose_name': 'Régimen Fiscal SAT (Legacy)', 'verbose_name_plural': 'Regímenes Fiscales SAT (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='satusocfdi',
            options={'verbose_name': 'Uso de CFDI SAT (Legacy)', 'verbose_name_plural': 'Usos de CFDI SAT (Legacy)'},
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='contabilida_uuid_2d5cd9_idx',
            old_name='contabilida_uuid_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='contabilida_estado_af8786_idx',
            old_name='contabilida_estado_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='contabilida_cliente_20a5c7_idx',
            old_name='contabilida_cliente_fecha_idx',
        ),
        migrations.RemoveField(
            model_name='satformapago',
            name='bancarizado',
        ),
        migrations.RemoveField(
            model_name='satformapago',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='satmetodopago',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='satregimenfiscal',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='satregimenfiscal',
            name='fisica',
        ),
        migrations.RemoveField(
            model_name='satregimenfiscal',
            name='moral',
        ),
        migrations.RemoveField(
            model_name='satusocfdi',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='satusocfdi',
            name='fisica',
        ),
        migrations.RemoveField(
            model_name='satusocfdi',
            name='moral',
        ),
        migrations.AddField(
            model_name='factura',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='satformapago',
            name='clave',
            field=models.CharField(default='00', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='satmetodopago',
            name='clave',
            field=models.CharField(default='000', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='satregimenfiscal',
            name='clave',
            field=models.CharField(default='000', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='satusocfdi',
            name='clave',
            field=models.CharField(default='000', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='certificadodigital',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='certificadodigital',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='certificadodigital',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='certificadodigital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='certificadodigital',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='cfdiclaveprodserv',
            name='clave',
            field=models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cfdiformapago',
            name='clave',
            field=models.CharField(default='00', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cfdimetodopago',
            name='clave',
            field=models.CharField(default='000', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cfdiunidad',
            name='clave',
            field=models.CharField(default='000', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cfdiusocfdi',
            name='clave',
            field=models.CharField(default='000', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='contabilidad.cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estimacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='obras.estimacion'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='satmetodopago',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='satregimenfiscal',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='satusocfdi',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='satformapago',
            table='contabilidad_satformapago',
        ),
        migrations.AlterModelTable(
            name='satmetodopago',
            table='contabilidad_satmetodopago',
        ),
        migrations.AlterModelTable(
            name='satregimenfiscal',
            table='contabilidad_satregimenfiscal',
        ),
        migrations.AlterModelTable(
            name='satusocfdi',
            table='contabilidad_satusocfdi',
        ),
    ]
