# Generated by Django 6.0 on 2026-01-04 05:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_alter_satformapago_options_and_more'),
        ('core', '0002_featureflag_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('serie', models.CharField(blank=True, max_length=25, null=True)),
                ('folio', models.CharField(max_length=40)),
                ('fecha', models.DateTimeField()),
                ('fecha_pago', models.DateTimeField(help_text='Fecha en que se realizó el pago')),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=19)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total del pago', max_digits=19)),
                ('numero_operacion', models.CharField(blank=True, help_text='Número de cheque, transferencia, etc.', max_length=100, null=True)),
                ('rfc_emisor_cuenta_ordenante', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_banco_ordenante', models.CharField(blank=True, max_length=300, null=True)),
                ('cuenta_ordenante', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc_emisor_cuenta_beneficiaria', models.CharField(blank=True, max_length=13, null=True)),
                ('cuenta_beneficiaria', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('xml_original', models.TextField(blank=True, null=True)),
                ('xml_timbrado', models.TextField(blank=True, null=True)),
                ('cadena_original', models.TextField(blank=True, null=True)),
                ('sello_digital', models.TextField(blank=True, null=True)),
                ('sello_sat', models.TextField(blank=True, null=True)),
                ('numero_certificado_sat', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('TIMBRADO', 'Timbrado'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error')], default='BORRADOR', max_length=20)),
                ('pdf_archivo', models.FileField(blank=True, null=True, upload_to='complementos_pago/pdf/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa')),
                ('factura', models.ForeignKey(blank=True, help_text='Factura original que se está pagando', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complementos_pago', to='contabilidad.factura')),
                ('forma_pago', models.ForeignKey(help_text='Forma de pago (01-Efectivo, 03-Transferencia, etc.)', on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cfdiformapago')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Complemento de Pago',
                'verbose_name_plural': 'Complementos de Pago',
                'db_table': 'contabilidad_complementopago',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRelacionadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.UUIDField(help_text='UUID de la factura que se paga')),
                ('serie', models.CharField(blank=True, max_length=25, null=True)),
                ('folio', models.CharField(max_length=40)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('numero_parcialidad', models.IntegerField(help_text='Número de parcialidad (1, 2, 3...)')),
                ('importe_saldo_anterior', models.DecimalField(decimal_places=2, help_text='Saldo insoluto antes de este pago', max_digits=19)),
                ('importe_pagado', models.DecimalField(decimal_places=2, help_text='Importe pagado en esta parcialidad', max_digits=19)),
                ('importe_saldo_insoluto', models.DecimalField(decimal_places=2, help_text='Saldo pendiente después de este pago', max_digits=19)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=6, default=Decimal('1.0'), max_digits=19, null=True)),
                ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_relacionados', to='contabilidad.complementopago')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='contabilidad.factura')),
                ('metodo_pago', models.ForeignKey(help_text='Método de pago del documento (PUE/PPD)', on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cfdimetodopago')),
            ],
            options={
                'verbose_name': 'Documento Relacionado',
                'verbose_name_plural': 'Documentos Relacionados',
                'db_table': 'contabilidad_documentorelacionadopago',
                'ordering': ['numero_parcialidad'],
            },
        ),
    ]
