# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_add_complemento_pago'),
    ]

    operations = [
        # Índices para Factura
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(
                fields=['empresa', 'fecha', 'estado'],
                name='fact_emp_fec_est_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(
                fields=['cliente', 'fecha'],
                name='fact_cli_fec_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(
                fields=['uuid'],
                name='fact_uuid_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(
                fields=['estado', 'fecha'],
                name='fact_est_fec_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(
                fields=['-fecha'],  # Descendente para queries recientes
                name='fact_fec_desc_idx'
            ),
        ),
    ]
