# Generated by Django 6.0 on 2026-01-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featureflag_systemsetting'),
        ('ia', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='knowledgebase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='core.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebase',
            unique_together={('source_app', 'source_model', 'source_id', 'empresa')},
        ),
    ]
