# Generated by Django 6.0 on 2025-12-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_almacen_movimientoinventario_existencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ultimo_costo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
