# Generated by Django 6.0 on 2026-01-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_requisicion_detallerequisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='requisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='compras.requisicion'),
        ),
    ]
