# Generated by Django 6.0 on 2026-01-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_ordencompra_empresa_recepcioncompra_empresa'),
        ('core', '0002_featureflag_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Alerta si la existencia global cae debajo de este valor', max_digits=12),
        ),
    ]
