# Generated by Django 6.0 on 2026-01-04 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_almacen_empresa_insumo_stock_minimo'),
        ('inventarios', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerecepcion',
            name='almacen_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.almacen'),
        ),
        migrations.AlterUniqueTogether(
            name='existencia',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'permissions': [('aprobar_sobrecosto', 'Puede aprobar ODC sin presupuesto')]},
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='xml_uuid',
            field=models.CharField(blank=True, help_text='UUID del XML de la factura SAT', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(choices=[('ACERO', 'Acero'), ('CONCRETO', 'Concreto'), ('PAPELERIA', 'Papelería'), ('MAQUINARIA', 'Maquinaria'), ('FERRETERIA', 'Ferretería'), ('SERVICIOS', 'Servicios'), ('OTROS', 'Otros')], default='OTROS', max_length=20),
        ),
        migrations.DeleteModel(
            name='Almacen',
        ),
        migrations.DeleteModel(
            name='Existencia',
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
    ]
