# Generated by Django 5.2.4 on 2025-08-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="passkey_credentials",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
