# Generated by Django 6.0 on 2025-12-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_inactive_users', 'Can view inactive users'), ('hard_delete_customuser', 'Can hard delete custom users')]},
        ),
    ]
