# Generated by Django 6.0 on 2025-12-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_customuser_created_at_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_inactive_users', 'Can view inactive users'), ('hard_delete_customuser', 'Can hard delete custom users'), ('view_consolidado', 'Can view consolidated reports across companies')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='empresa_principal',
            field=models.ForeignKey(blank=True, help_text='Empresa por defecto al iniciar sesión', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_principales', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='empresas_acceso',
            field=models.ManyToManyField(blank=True, help_text='Empresas a las que tiene acceso este usuario', related_name='usuarios_con_acceso', to='core.empresa'),
        ),
    ]
