# Generated by Django 6.0 on 2025-12-17 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ultima_empresa_activa',
            field=models.ForeignKey(blank=True, help_text='Última empresa seleccionada por el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activos', to='core.empresa'),
        ),
    ]
