# Generated by Django 6.0 on 2025-12-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_inactive_records', 'Can view inactive records globally'), ('hard_delete_records', 'Can hard delete records globally'), ('view_consolidado', 'Can view consolidated reports across companies'), ('use_ai', 'Can use AI features')]},
        ),
    ]
