# Generated by Django 6.0 on 2025-12-24 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_session_device',
            field=models.CharField(blank=True, help_text='Dispositivo de la sesión actual', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_version',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
