# Generated by Django 6.0 on 2025-12-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_dashboard', 'Ver Dashboard'), ('view_inactive_records', 'Ver registros inactivos globalmente'), ('hard_delete_records', 'Eliminar permanentemente registros'), ('view_consolidado', 'Ver reportes consolidados entre empresas'), ('use_ai', 'Usar funciones de IA'), ('view_inactive_users', 'Ver usuarios inactivos'), ('hard_delete_customuser', 'Eliminar permanentemente usuarios')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
