# Generated by Django 6.0 on 2025-12-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totp_authorization_configured',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha configurado su TOTP de autorización'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_authorization_secret',
            field=models.CharField(blank=True, help_text='Secreto TOTP para autorización de operaciones sensibles (cancelaciones, devoluciones, etc.)', max_length=255, null=True),
        ),
    ]
