# Generated by Django 4.2.27 on 2025-12-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_totp_authorization_configured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_dashboard', 'Ver Panel Principal (Dashboard)'), ('view_inactive_records', 'Ver registros inactivos en todo el sistema'), ('hard_delete_records', 'Eliminar permanentemente registros (sin recuperación)'), ('view_consolidado', 'Ver reportes consolidados multi-empresa'), ('use_ai', 'Usar asistente de Inteligencia Artificial'), ('manage_ai_settings', 'Configurar parámetros de IA'), ('view_inactive_users', 'Ver usuarios inactivos o suspendidos'), ('hard_delete_customuser', 'Eliminar permanentemente usuarios'), ('impersonate_users', 'Iniciar sesión como otro usuario (impersonar)'), ('manage_user_permissions', 'Gestionar permisos de usuarios'), ('reset_user_credentials', 'Restablecer credenciales de acceso'), ('view_audit_logs', 'Ver registros de auditoría'), ('export_audit_logs', 'Exportar registros de auditoría'), ('view_security_alerts', 'Ver alertas de seguridad'), ('access_all_companies', 'Acceder a todas las empresas del sistema'), ('switch_company_context', 'Cambiar contexto de empresa activa')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
