# Generated by Django 6.0 on 2025-12-30 21:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0012_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_dashboard', 'Ver Panel Principal (Dashboard)'), ('view_inactive_records', 'Ver registros inactivos'), ('hard_delete_records', 'Eliminar permanentemente registros'), ('view_consolidado', 'Ver reportes consolidados multi-empresa'), ('use_ai', 'Usar asistente de IA'), ('manage_ai_settings', 'Configurar parámetros de IA'), ('view_inactive_users', 'Ver usuarios inactivos o suspendidos'), ('hard_delete_customuser', 'Eliminar permanentemente usuarios'), ('impersonate_users', 'Impersonar usuarios'), ('manage_user_permissions', 'Gestionar permisos de usuarios'), ('reset_user_credentials', 'Restablecer credenciales de acceso'), ('access_all_companies', 'Acceder a todas las empresas'), ('switch_company_context', 'Cambiar contexto de empresa activa')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='totp_authorization_secret',
            field=models.CharField(blank=True, help_text='Secreto TOTP para autorización de operaciones sensibles', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_sistema', models.BooleanField(default=False, help_text='Indica si es un rol protegido del sistema (no editable)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permisos que otorga este rol', related_name='roles', to='auth.permission')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles asignados a este usuario', related_name='users', to='users.role'),
        ),
    ]
