# Generated by Django 6.0 on 2026-01-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='empresas_acceso',
            new_name='empresas',
        ),
    ]
