# Generated by Django 6.0 on 2026-01-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_empresas_acceso_customuser_empresas'),
    ]

    operations = [
    ]
