# Generated by Django 6.0 on 2026-01-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featureflag_systemsetting'),
        ('users', '0015_auto_20260103_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='empresas',
            field=models.ManyToManyField(blank=True, db_table='users_customuser_empresas', help_text='Empresas a las que tiene acceso este usuario', related_name='usuarios_con_acceso', to='core.empresa'),
        ),
    ]
