# Generated by Django 6.0 on 2025-12-17 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(help_text='Código único de la empresa (ej: LUX01, LUX02)', max_length=10, unique=True)),
                ('razon_social', models.CharField(help_text='Razón social completa según acta constitutiva', max_length=200)),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial o marca', max_length=100)),
                ('rfc', models.CharField(help_text='RFC de la empresa', max_length=13, unique=True)),
                ('regimen_fiscal', models.CharField(help_text='Código de régimen fiscal SAT (ej: 601, 612)', max_length=10)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(max_length=20)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('colonia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Logo de la empresa para documentos', null=True, upload_to='empresas/logos/')),
                ('color_primario', models.CharField(default='#3B82F6', help_text='Color principal en formato hex (#RRGGBB)', max_length=7)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('serie_factura', models.CharField(blank=True, help_text='Serie por defecto para facturas (ej: A, B, F)', max_length=10, null=True)),
                ('folio_inicial', models.IntegerField(default=1, help_text='Folio inicial para documentos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['codigo'],
            },
        ),
    ]
