# Generated by Django 6.0 on 2026-01-03 17:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(db_index=True, help_text="Código único del feature (ej: 'MODULE_OBRAS')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo del feature', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción de qué hace este feature')),
                ('is_active', models.BooleanField(default=False, help_text='Si el feature está activo globalmente')),
                ('rollout_percentage', models.IntegerField(default=100, help_text='Porcentaje de usuarios que ven el feature (0-100). Para A/B testing.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='Lista de roles que tienen acceso (opcional)')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Usuarios específicos que tienen acceso (opcional)', related_name='feature_flags', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó este feature flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='core_featur_code_ef533a_idx'), models.Index(fields=['is_active'], name='core_featur_is_acti_ffc139_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('key', models.CharField(db_index=True, help_text="Clave única de configuración (ej: 'POS_ALLOW_NEGATIVE_STOCK')", max_length=100, unique=True)),
                ('value', models.JSONField(help_text='Valor de la configuración (puede ser bool, string, int, dict, list)')),
                ('category', models.CharField(choices=[('FISCAL', 'Fiscal y Contabilidad'), ('POS', 'Punto de Venta'), ('INVENTARIO', 'Inventario y Almacenes'), ('RRHH', 'Recursos Humanos'), ('SECURITY', 'Seguridad'), ('GENERAL', 'General'), ('INTEGRACIONES', 'Integraciones')], db_index=True, default='GENERAL', help_text='Categoría para agrupar configuraciones', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Descripción de qué hace esta configuración')),
                ('is_public', models.BooleanField(default=False, help_text='Si True, se envía al frontend en el arranque')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, help_text='Último usuario que modificó esta configuración', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_modified', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['key'], name='core_system_key_f40380_idx'), models.Index(fields=['category'], name='core_system_categor_c152a0_idx'), models.Index(fields=['is_public'], name='core_system_is_publ_397ec9_idx')],
            },
        ),
    ]
