# Generated by Django 6.0 on 2025-12-19 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('contabilidad', '0004_centrocostos_cuentacontable_poliza_detallepoliza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura (CR Normal)'), ('ANTICIPO', 'Anticipo (Sin Factura)'), ('GASTO_VIAJE', 'Gasto de Viaje'), ('REEMBOLSO', 'Reembolso')], default='FACTURA', max_length=20)),
                ('xml_archivo', models.FileField(blank=True, null=True, upload_to='facturas/xml/')),
                ('pdf_archivo', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('uuid', models.CharField(blank=True, help_text='Folio Fiscal del XML', max_length=36, null=True, unique=True)),
                ('fecha_recepcion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado (Listo para Pago)'), ('PROGRAMADO', 'Programado'), ('PAGADO_PARCIAL', 'Pagado Parcialmente'), ('PAGADO', 'Pagado Totalmente'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.moneda')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrarecibos', to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrarecibos', to='compras.proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_programada', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('cuenta_emisora', models.CharField(max_length=50)),
                ('total_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADA', 'Autorizada'), ('PROCESADA', 'Procesada (Layout Generado)'), ('PAGADA', 'Pagada (Confirmada)')], default='BORRADOR', max_length=20)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('banco_emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.banco')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contra_recibo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.contrarecibo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tesoreria.programacionpago')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
