# Generated by Django 6.0 on 2025-12-27 20:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_tipocambio_unique_together_and_more'),
        ('core', '0001_initial'),
        ('tesoreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(help_text='Nombre de la caja (ej: Caja Oficina Central)', max_length=100)),
                ('monto_fondo', models.DecimalField(decimal_places=2, help_text='Monto del fondo fijo', max_digits=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('REEMBOLSADA', 'Reembolsada')], default='ABIERTA', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_chicas', to='core.empresa')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_responsable', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Caja Chica',
                'verbose_name_plural': 'Cajas Chicas',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_cuenta', models.CharField(help_text='Número de cuenta', max_length=20)),
                ('clabe', models.CharField(blank=True, help_text='CLABE interbancaria', max_length=18, null=True)),
                ('tipo_cuenta', models.CharField(choices=[('CHEQUES', 'Cuenta de Cheques'), ('INVERSION', 'Cuenta de Inversión'), ('NOMINA', 'Cuenta de Nómina'), ('AHORRO', 'Cuenta de Ahorro')], default='CHEQUES', max_length=20)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, help_text='Saldo según sistema', max_digits=16)),
                ('saldo_bancario', models.DecimalField(decimal_places=2, default=0, help_text='Saldo según estado de cuenta', max_digits=16)),
                ('es_principal', models.BooleanField(default=False, help_text='Cuenta principal para operaciones')),
                ('activa', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_empresa', to='contabilidad.banco')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuenta_contable', models.ForeignKey(blank=True, help_text='Cuenta contable asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.cuentacontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='core.empresa')),
                ('moneda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.moneda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'permissions': [('autorizar_egreso', 'Autorizar Egresos'), ('realizar_pago', 'Realizar Pagos'), ('conciliar_banco', 'Conciliar Cuentas Bancarias'), ('cerrar_caja', 'Cerrar Caja Chica')],
                'unique_together': {('banco', 'numero_cuenta')},
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta')], default='TRANSFERENCIA', max_length=20)),
                ('beneficiario', models.CharField(max_length=200)),
                ('concepto', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(blank=True, help_text='Número de cheque o referencia bancaria', max_length=50, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='egresos/comprobantes/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADO', 'Autorizado'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('contra_recibo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='tesoreria.contrarecibo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='tesoreria.cuentabancaria')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('GASTO', 'Gasto'), ('REEMBOLSO', 'Reembolso')], max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='cajas_chicas/comprobantes/')),
                ('beneficiario', models.CharField(blank=True, max_length=200, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tesoreria.cajachica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
