# Generated by Django 4.2.27 on 2025-12-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_cajachica_cuentabancaria_egreso_movimientocaja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentabancaria',
            options={'permissions': [('view_bank_balances', 'Ver saldos bancarios'), ('conciliate_bank', 'Conciliar cuentas bancarias'), ('register_bank_movement', 'Registrar movimientos bancarios'), ('create_payment_request', 'Solicitar pagos'), ('authorize_payment', 'Autorizar pagos y egresos'), ('execute_payment', 'Ejecutar pagos (emitir cheques/transferencias)'), ('void_payment', 'Anular pagos emitidos'), ('manage_petty_cash', 'Gestionar caja chica'), ('close_petty_cash', 'Cerrar y reembolsar caja chica'), ('approve_petty_cash_expense', 'Aprobar gastos de caja chica'), ('view_cash_flow', 'Ver flujo de efectivo'), ('create_cash_projection', 'Crear proyecciones de flujo'), ('view_treasury_reports', 'Ver reportes de tesorería'), ('export_treasury_reports', 'Exportar reportes de tesorería')], 'verbose_name': 'Cuenta Bancaria', 'verbose_name_plural': 'Cuentas Bancarias'},
        ),
    ]
