# Generated by Django 6.0 on 2025-12-30 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_alter_certificadodigital_archivo_cer_and_more'),
        ('tesoreria', '0003_alter_cuentabancaria_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajachica',
            options={'permissions': [('manage_petty_cash', 'Gestionar caja chica'), ('close_petty_cash', 'Cerrar y reembolsar caja chica'), ('approve_petty_cash_expense', 'Aprobar gastos de caja chica')], 'verbose_name': 'Caja Chica', 'verbose_name_plural': 'Cajas Chicas'},
        ),
        migrations.AlterModelOptions(
            name='cuentabancaria',
            options={'permissions': [('view_bank_balances', 'Ver saldos bancarios'), ('conciliate_bank', 'Conciliar cuentas bancarias'), ('register_bank_movement', 'Registrar movimientos bancarios'), ('create_payment_request', 'Solicitar pagos'), ('authorize_payment', 'Autorizar pagos y egresos'), ('execute_payment', 'Ejecutar pagos (emitir cheques/transferencias)'), ('void_payment', 'Anular pagos emitidos'), ('view_treasury_reports', 'Ver reportes de tesorería'), ('export_treasury_reports', 'Exportar reportes de tesorería')], 'verbose_name': 'Cuenta Bancaria', 'verbose_name_plural': 'Cuentas Bancarias'},
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_tesoreria', to='contabilidad.banco'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable asociada (ej: 1020-001 Bancos BBVA)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], default='MXN', max_length=3),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo según sistema (se recalcula con movimientos)', max_digits=16),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldo_bancario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo según estado de cuenta (para conciliación)', max_digits=16),
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(max_length=50)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('codigo_sat', models.CharField(blank=True, help_text='Código SAT del banco', max_length=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha', models.DateField(help_text='Fecha del movimiento')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(blank=True, help_text='Referencia bancaria, número de cheque, etc.', max_length=100, null=True)),
                ('beneficiario', models.CharField(blank=True, help_text='Nombre del beneficiario o pagador', max_length=200, null=True)),
                ('concepto', models.CharField(help_text='Descripción del movimiento', max_length=300)),
                ('origen_tipo', models.CharField(choices=[('POS_TURNO', 'Cierre de Turno POS'), ('CXC_PAGO', 'Pago de Cliente (CxC)'), ('CXP_PAGO', 'Pago a Proveedor (CxP)'), ('NOMINA', 'Dispersión de Nómina'), ('MANUAL', 'Movimiento Manual'), ('CONCILIACION', 'Ajuste de Conciliación'), ('OTRO', 'Otro')], default='MANUAL', max_length=20)),
                ('origen_id', models.IntegerField(blank=True, help_text='ID del registro origen (ej: ID de Turno, ID de Pago)', null=True)),
                ('conciliado', models.BooleanField(default=False, help_text='Indica si el movimiento ya fue conciliado con el estado de cuenta')),
                ('fecha_conciliacion', models.DateTimeField(blank=True, null=True)),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_conciliados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tesoreria.cuentabancaria')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='egreso',
            name='movimiento_bancario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egreso', to='tesoreria.movimientobancario'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['cuenta', 'fecha'], name='tesoreria_m_cuenta__0dfc64_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['conciliado'], name='tesoreria_m_concili_0d2d48_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['origen_tipo', 'origen_id'], name='tesoreria_m_origen__ba6a35_idx'),
        ),
    ]
