# Generated by Django 6.0 on 2026-01-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_porcentaje_anticipo_and_more'),
        ('tesoreria', '0004_alter_cajachica_options_alter_cuentabancaria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_actividad', to='obras.actividadproyecto'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_financieros', to='obras.obra'),
        ),
    ]
