# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_egreso_actividad_egreso_obra'),
    ]

    operations = [
        # Índices para Egreso
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(
                fields=['empresa', 'fecha'],
                name='egr_emp_fec_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(
                fields=['obra', 'fecha'],
                name='egr_obra_fec_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(
                fields=['-fecha'],  # Descendente
                name='egr_fec_desc_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(
                fields=['tipo_egreso', 'fecha'],
                name='egr_tipo_fec_idx'
            ),
        ),
    ]
