# Generated by Django 6.0 on 2025-12-30 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('EXPORT', 'Exportación de Datos'), ('IMPORT', 'Importación de Datos'), ('APPROVE', 'Aprobación'), ('REJECT', 'Rechazo'), ('CANCEL', 'Cancelación')], help_text='Tipo de acción realizada', max_length=20)),
                ('object_id', models.CharField(blank=True, help_text='ID del objeto afectado', max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, help_text='Representación en texto del objeto', max_length=500)),
                ('cambios', models.JSONField(blank=True, help_text="Diccionario con los cambios: {'campo': {'old': valor_anterior, 'new': valor_nuevo}}", null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent del navegador/dispositivo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la acción')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de la acción')),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo de modelo afectado', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
                'permissions': [('view_audit_logs', 'Ver registros de auditoría'), ('export_audit_logs', 'Exportar registros de auditoría'), ('delete_audit_logs', 'Eliminar registros de auditoría')],
                'indexes': [models.Index(fields=['-fecha'], name='auditoria_a_fecha_46adfa_idx'), models.Index(fields=['usuario', '-fecha'], name='auditoria_a_usuario_cebed2_idx'), models.Index(fields=['content_type', '-fecha'], name='auditoria_a_content_193494_idx'), models.Index(fields=['accion', '-fecha'], name='auditoria_a_accion_cecdb1_idx'), models.Index(fields=['content_type', 'object_id'], name='auditoria_a_content_2f8c97_idx')],
            },
        ),
    ]
